title: Jordan E. Kearschner - Portfolio
url: "https://jjekea.github.io"
baseurl: "/portfolio"
remote_theme: jekyll/minima@1e8a445
plugins:
- jekyll-remote-theme
title: Jordan E. Kearschner - Portfolio
